Adjust on list price update with cny_rate
yostashiro/awo-custom pull request #4
Opened 2017-03-17 05:28 UTC by eHanseFrank

- adding a new calculated field to product.template: net_price_rmb which uses cny_rate in its compute method [NOT WORKING]
- further adjustments to the attribute order in view

2017-03-20 03:04 UTC, yostashiro requested changes
@eHanseFrank I've added comments.  Please review and update your code. :D

2017-03-20 03:04 UTC, yostashiro commented on product_listprice_list_view/models/product_template.py
> +    @api.depends('cny_rate','net_price')
No need to have `@api.depends` for computation for non-stored field

2017-03-20 03:04 UTC, yostashiro commented on product_listprice_list_view/models/product_template.py
> +            pt.net_price_rnb = pt.net_price * pt.cny_rate
Typo here - should be `pt.net_price_rmb` instead of `pt.net_price_rnb`

2017-03-20 03:04 UTC, yostashiro commented on product_listprice_list_view/models/product_template.py
> +            pt.net_price_rnb = pt.net_price * pt.cny_rate
I would actually include this calculation in `_get_cny_rate` method

2017-03-20 03:04 UTC, yostashiro commented on product_listprice_list_view/views/product_template_views.xml
> +                    <field name="qty_available" string="Qty internal"/>
Add `widget="integer"`?

2017-03-30 11:05 UTC, yostashiro commented
@eHanseFrank Are you still following up on this topic?

2017-03-30 11:10 UTC, eHanseFrank commented
You can close this. Thanks


Am 30-03-2017 um 7:05 PM schrieb Yoshi Tashiro:
>
> @eHanseFrank <https://github.com/eHanseFrank> Are you still following 
> up on this topic?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/yostashiro/awo-custom/pull/4#issuecomment-290378728>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/AKqR6qtIDspKhCF4cz8DR_Saa7DGDK2Fks5rq4yHgaJpZM4MgMXd>.
>

2017-03-30 11:16 UTC, closed without merging